# Generated by Django 2.2.12 on 2023-01-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('bentangalam', models.CharField(max_length=100)),
                ('koordinat', models.FloatField(max_length=100)),
            ],
        ),
    ]
