# Generated by Django 2.2.12 on 2023-01-03 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jabar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kota',
            old_name='bentangalam',
            new_name='bentang_alam',
        ),
    ]
