# Generated by Django 2.2.12 on 2023-01-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jabar', '0002_auto_20230103_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('bentang_alam', models.CharField(max_length=100)),
                ('x', models.IntegerField(null=True)),
                ('y', models.IntegerField(null=True)),
            ],
        ),
    ]
