# Generated by Django 2.2.12 on 2023-01-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jabar', '0003_peta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peta',
            name='x',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='peta',
            name='y',
            field=models.CharField(max_length=100),
        ),
    ]
